name: CI Build & Test

# main에 pr시 ci 동작
on:
  pull_request:
    branches: [main,develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./spring/gradlew

      - name: Set DB_PW and CAP_KEY from Secrets
        run: |
          echo "DB_PW=${{ secrets.DB_PW }}" >> $GITHUB_ENV
          echo "CAP_KEY=${{ secrets.CAP_KEY }}" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build and Test
        working-directory: ./spring
        #임시로 test 제외하고 빌드

#        run: ./gradlew clean build -x test
        #test 포함 코드
        run: ./gradlew clean build

